# Page specs for MSP Chauffeur Service service pages. Copy is original, paraphrased from the reference site's structure.
R = {
    'hub': ('airport-car-service.html', 'Airport Car Service', 'Every kind of MSP transfer, compared.'),
    'black': ('msp-airport-black-car-service.html', 'MSP Airport Black Car Service', 'Terminal-by-terminal pickup, flight tracking, fixed fares.'),
    'pickup': ('airport-pickup.html', 'Airport Pickup', 'A straightforward ride from baggage claim to your door.'),
    'mpls': ('minneapolis-car-service.html', 'Black Car Service in Minneapolis', 'Private, pre-arranged, chauffeur-driven.'),
    'corp': ('corporate-car-service.html', 'Corporate Car Service', 'One invoice, saved travelers, a dedicated contact.'),
    'limo': ('limousine-service-minneapolis.html', 'Limo Service in Minneapolis', 'The limo standard, in a sedan, SUV or Sprinter.'),
    'hourly': ('hourly-car-service.html', 'Hourly Car Service', 'A car and chauffeur for a block of time.'),
    'chauffeur': ('private-chauffeur-service.html', 'Private Chauffeur Service', 'As-directed driving for a full day.'),
    'p2p': ('point-to-point-transportation.html', 'Point-to-Point Transportation', 'Door to door, one flat rate.'),
    'group': ('group-transportation.html', 'Group Transportation', 'Sprinter vans and multi-vehicle coordination.'),
    'downtown': ('downtown-twin-cities-black-car.html', 'Downtown Twin Cities', 'Minneapolis and Saint Paul, curb to door.'),
    'crew': ('flight-crew-charter-service.html', 'Flight Crew Charter Service', 'Crew transport built around reporting times.'),
    'mayo': ('mayo-clinic-transportation.html', 'Mayo Clinic Transportation', 'Minneapolis to Rochester, private and direct.'),
    'chmpls': ('chauffeur-service-minneapolis.html', 'Chauffeur Service in Minneapolis', 'A dedicated professional, not just a ride.'),
    'moa': ('mall-of-america-car-service.html', 'Mall of America Car Service', 'Bloomington, MOA and MSP, door to door.'),
    'area': ('service-area.html', 'Service Area', 'Anywhere you need to go.'),
    'rental': ('car-rental-msp-airport.html', 'Car Service vs. Rental', 'Skip the counter and the ice scraper.'),
    'fleet': ('fleet.html', 'Our Fleet', 'Sedan, SUV, Premium SUV, Sprinter.'),
}
def rel(*keys): return [(R[k][0], R[k][1], R[k][2]) for k in keys]

PAGES = [
# ---------------------------------------------------------------- 1. Airport car service hub
dict(file=R['hub'][0], title='Airport Car Service Minneapolis | MSP Transfers Compared | MSP Chauffeur Service', title_short='Airport Car Service',
     meta='Airport car service for MSP: black car transfers, airport pickup, group Sprinter vans and flight crew transport. Compare the options and book the right one the first time.',
     keywords='airport car service Minneapolis, MSP airport transportation, MSP car service, airport black car MSP, airport transfer Minneapolis', service_type='Airport car service',
     eyebrow='Airport Transportation · MSP', h1='Airport Car Service for <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Minneapolis–Saint Paul</span>',
     lede='"Airport transportation" covers a few different trips. Here is how ours break down, so you can book the right one the first time and never stand at a curb wondering where your car is.',
     image='images/site/svc-airport-hub.webp', image_alt='Black Escalade and Yukon staged at the MSP departures curb at dusk with a chauffeur standing by', image_caption='Terminal 1 · Terminal 2 · FBO Ramps',
     intro_eyebrow='Which Trip Is Yours?', intro_h2='Four airport services, one standard',
     intro=['Flying solo or with one or two others and want a chauffeur assigned to you before you land? Start with our <a href="msp-airport-black-car-service.html" class="text-brass-300 hover:text-ivory-100 underline underline-offset-2">MSP Airport Black Car Service</a>, the most detailed page we have, covering terminal-by-terminal pickup, flight tracking and pricing.',
            'Just need a clean, on-time ride after you land? <a href="airport-pickup.html" class="text-brass-300 hover:text-ivory-100 underline underline-offset-2">Airport Pickup</a> is exactly that. Traveling with seven or more, or coordinating a wedding party or team? See <a href="group-transportation.html" class="text-brass-300 hover:text-ivory-100 underline underline-offset-2">Group Transportation</a>. Arriving as airline crew? <a href="flight-crew-charter-service.html" class="text-brass-300 hover:text-ivory-100 underline underline-offset-2">Flight Crew Charter</a> is built around your schedule.',
            'Still not sure? Call (612) 666-5004 and dispatch will point you to the right option in about a minute.'],
     bullets_eyebrow='Compare', bullets_h2='Pick by group size and how much detail you want',
     bullets=[('MSP Airport Black Car', 'Solo travelers, couples and small groups. A chauffeur assigned in advance, live flight tracking, a rate quoted before you confirm, and pickup at either terminal, 24 hours a day.'),
              ('Airport Pickup', 'The no-fuss version. Tell us the flight, we time the car to it and meet you at baggage claim or the curb. Same chauffeurs, same fixed fare.'),
              ('Group Transportation', 'Sprinter vans for seven to ten with luggage, and coordinated multi-vehicle pickups when a group lands on different flights.'),
              ('Flight Crew Charter', 'Scheduled ground transport built around crew rest and reporting requirements, with reliable timing between hotels and terminals.')],
     steps_eyebrow='Every Reservation Includes', steps_h2='What comes standard on any airport trip',
     steps=[('A chauffeur assigned in advance', 'Committed at booking, not matched at the curb by an app.'), ('A rate quoted upfront', 'It does not move for weather, traffic or demand.'),
            ('Real-time flight tracking', 'A delayed inbound changes our pickup time, not your plans, with a free 15-minute hold after landing.'), ('Luggage handled', 'From the curb to the trunk and back again at drop-off.')],
     faq=[('What is the difference between MSP Airport Black Car Service and Airport Pickup?', 'Black Car Service is the most detailed option: terminal-by-terminal pickup, flight tracking and pricing for solo travelers, couples and small groups. Airport Pickup is the faster, no-frills ride timed to your flight for travelers who simply need a lift from baggage claim to their destination. Both use the same chauffeurs and fixed fares.'),
          ('Which service should I book for a group of seven or more?', 'Group Transportation. It uses our Mercedes Sprinter for up to ten passengers with luggage, and we coordinate more than one vehicle when a group is split across flights.'),
          ('Do you serve flight crews differently?', 'Yes. Flight Crew Charter Service is scheduled ground transportation built around airline crew rest and reporting requirements, with recurring hotel and terminal transfers.'),
          ('Can I switch services after booking if my plans change?', 'Yes. Call dispatch and we will move your reservation to the service that fits, whether your group size changes or your flight plans shift.'),
          ('Do you serve both MSP terminals?', 'Yes. Terminal 1 (Lindbergh) and Terminal 2 (Humphrey), arrivals and departures, every hour of every day.')],
     related=rel('black', 'pickup', 'group', 'crew'), cta_h2='Your flight is booked. The ride should be the easy part.', cta_p='Reserve online in about two minutes, or call dispatch and we will match you to the right service.'),

# ---------------------------------------------------------------- 2. MSP airport black car
dict(file=R['black'][0], title='MSP Airport Black Car Service | Flight-Tracked, Fixed Fare | MSP Chauffeur Service', title_short='MSP Airport Black Car Service',
     meta='Private black car service to and from MSP Airport. Chauffeur assigned in advance, real-time flight tracking, Terminal 1 and Terminal 2 pickup, fixed all-inclusive fares from $60.',
     keywords='MSP airport black car service, black car to MSP, Minneapolis airport car service, MSP airport chauffeur, Terminal 1 pickup, Terminal 2 pickup', service_type='Airport black car service',
     eyebrow='Flight-Tracked · Fixed Fare · 24/7', h1='MSP Airport <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Black Car Service</span>',
     lede='Private, pre-arranged ground transportation in a late-model luxury vehicle with a professional chauffeur. Your car is assigned before you land, your rate is fixed before you confirm, and your flight is watched so you never have to.',
     image='images/site/svc-msp-black-car.webp', image_alt='Chauffeur smiling while holding open the rear door of a black GMC Yukon at the MSP terminal curb in the evening', image_caption='Assigned in Advance · Staged Ten Minutes Early',
     intro_eyebrow='What It Is', intro_h2='Not a shared shuttle. Not an app.',
     intro=['Black car service is a dedicated vehicle and a dedicated chauffeur reserved for your party alone. It differs from a shared shuttle or a rideshare in three ways that matter at 5 a.m.: the driver is committed to you at booking rather than matched at the curb, the price is agreed upfront and does not fluctuate, and the person behind the wheel is a licensed, background-checked professional who knows both terminals cold.',
            'Every reservation includes a chauffeur assigned in advance, a rate quoted before you confirm, real-time flight tracking with a free 15-minute hold after landing, and full luggage handling from curb to trunk and back.'],
     bullets_eyebrow='Terminal 1 and Terminal 2', bullets_h2='We know the drill at both terminals',
     bullets_lede='MSP runs two separate terminals about two miles apart. Tell us your airline and we handle the rest.',
     bullets=[('Terminal 1 · Lindbergh', 'Delta, American, United, Alaska and the international carriers. We meet you at the pre-arranged pickup area in the Ground Transportation Center, or inside baggage claim with a name sign if you add Meet & Greet.'),
              ('Terminal 2 · Humphrey', 'Sun Country, Southwest, JetBlue, Frontier and Spirit. Pickup at the ground transportation area by the Purple Ramp, with a text when your chauffeur is staged.'),
              ('Departures, timed right', 'For a domestic flight we generally plan to have you at the curb two hours ahead, three for international, adjusted for your terminal, checked bags and the time of day.')],
     steps_h2='How an MSP transfer works',
     steps=[('Book your ride', 'Reserve online or call with your flight number, pickup address and passenger count.'), ('We track your flight', 'Early, late or diverted, your pickup time follows the aircraft automatically.'),
            ('Chauffeur staged', 'Your chauffeur is positioned ten minutes early and texts you their name and vehicle.'), ('Walk out and go', 'Meet at the designated pickup area or inside baggage claim. Bags go in, you go home.')],
     faq=[('How far in advance should I book?', 'We recommend 24 hours for a standard transfer and three to five days for Sprinter vans, multi-vehicle groups or travel around major holidays and events. Same-day requests are often possible with a phone call to dispatch.'),
          ('What happens if my flight is delayed?', 'Nothing you need to manage. We track the inbound flight in real time and move the pickup automatically. There is no delay fee for a late arrival, and you get a free 15-minute hold once you land.'),
          ('Where will I meet my chauffeur at MSP?', 'At the pre-arranged commercial vehicle area in the Ground Transportation Center at Terminal 1, or the ground transportation area at Terminal 2. With Meet & Greet, your chauffeur waits inside baggage claim with a name sign.'),
          ('Is this a shared ride?', 'No. Every reservation is private. The vehicle is dedicated to you and your party with no other passengers and no stops you did not request.'),
          ('Do you provide child car seats?', 'Yes. Add up to four on the booking form, $25 each, and tell us the age and weight of each child so the correct seat is installed in advance.'),
          ('Do you offer long-distance service from MSP?', 'Yes. We regularly run MSP to Rochester and Mayo Clinic, Duluth, St. Cloud, Mankato and western Wisconsin, quoted as flat point-to-point fares.'),
          ('How do I pay?', 'By card online through Stripe when you book, or by cash or card with your chauffeur. Online payments show the card processing fee before you confirm.')],
     related=rel('pickup', 'hub', 'mayo', 'crew'), cta_h2='Put your name on the board tonight.', cta_p='Scheduled, confirmed and fixed-fare, whatever hour your flight keeps.'),

# ---------------------------------------------------------------- 3. Airport pickup
dict(file=R['pickup'][0], title='MSP Airport Pickup Service | Baggage Claim to Your Door | MSP Chauffeur Service', title_short='MSP Airport Pickup',
     meta='Airport pickup at Minneapolis–Saint Paul International. Flight-timed pickup at baggage claim or the curb, professional chauffeurs, fixed transparent pricing to Minneapolis, Saint Paul and every suburb.',
     keywords='MSP airport pickup, airport pickup Minneapolis, MSP pickup service, ride from MSP airport, airport transfer Minneapolis', service_type='Airport pickup service',
     eyebrow='Arrivals · Baggage Claim · Curbside', h1='MSP Airport Pickup, <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Timed to Your Flight</span>',
     lede='Arriving for business or a long weekend, the ride from MSP should be the simplest part. We watch the flight, meet you where you want to be met, and drive you straight to the door.',
     image='images/site/svc-airport-pickup.webp', image_alt='Smiling traveler with a suitcase greeted by a chauffeur beside a black Cadillac Escalade at the MSP arrivals curb', image_caption='Baggage Claim or Curbside · Your Call',
     intro_eyebrow='Where We Take You', intro_h2='Every neighborhood, every suburb',
     intro=['We provide airport pickup to every Minneapolis neighborhood, downtown, the University of Minnesota area, Bloomington, Edina, Saint Paul and the surrounding suburbs. Point-to-point transfers and hourly charters are both available.',
            'Your chauffeur is background-checked, knows both MSP terminals, and adjusts the pickup for delays and early landings without you lifting a finger. Fares are fixed and transparent with no hidden fees, from $60 for a sedan.'],
     bullets_eyebrow='Why Riders Choose It', bullets_h2='Built for the moment you land',
     bullets=[('On-time arrivals', 'Flight tracking and real-time updates mean we move the pickup for delays and early landings.'), ('Meet & Greet', 'Personal assistance inside baggage claim with a name sign, on request for $15.'),
              ('Professional chauffeurs', 'Background-checked, uniformed, with years of MSP experience and genuinely good manners.'), ('Comfort and privacy', 'A quiet, spotless late-model vehicle with climate control, water and chargers.'),
              ('Fixed pricing', 'The quote you see is the fare you pay, with no surge and no meter.'), ('Any hour', 'Red-eyes and first flights out are our specialty. Dispatch answers 24/7.')],
     steps_h2='How airport pickup works',
     steps=[('Book online or by phone', 'Give us your flight number and destination.'), ('We monitor your flight', 'Arrival time confirmed and the pickup adjusted automatically.'),
            ('Your chauffeur meets you', 'At baggage claim or the curb, and helps with luggage.'), ('A direct, comfortable ride', 'Straight to your Minneapolis destination, professional from start to finish.')],
     faq=[('Do you track my flight?', 'Yes. We monitor your inbound flight in real time and adjust the pickup for delays or early landings, so your chauffeur is ready when you walk out.'),
          ('Where do you meet me at MSP?', 'At baggage claim or curbside, whichever you prefer. Meet & Greet with a name sign is available on request.'),
          ('What areas do you serve?', 'All Minneapolis neighborhoods, downtown, the University area, Bloomington, Edina, Saint Paul and the surrounding suburbs, plus long-distance runs statewide.'),
          ('What vehicles are available?', 'Sedan, SUV, Premium SUV and a Sprinter van, sized to your passenger and luggage count.'),
          ('How do I pay?', 'By card at booking or with your chauffeur. Pricing is fixed and transparent with no hidden fees; the booking form shows your exact fare before you confirm.')],
     related=rel('black', 'hub', 'moa', 'downtown'), cta_h2='Land, walk out, and go.', cta_p='Reserve online in a minute or call dispatch. We are available around the clock.'),

# ---------------------------------------------------------------- 4. Minneapolis black car
dict(file=R['mpls'][0], title='Black Car Service in Minneapolis | Private Chauffeured Rides | MSP Chauffeur Service', title_short='Black Car Service in Minneapolis',
     meta='Private black car service in Minneapolis and Saint Paul. Chauffeur and vehicle assigned in advance, flat rates with no surge, late-model sedans, SUVs and Sprinter vans.',
     keywords='black car service Minneapolis, Minneapolis car service, luxury car service Minneapolis, private car service Twin Cities, chauffeured car Minneapolis', service_type='Black car service',
     eyebrow='Private · Pre-Arranged · Chauffeur-Driven', h1='Black Car Service in <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Minneapolis</span>',
     lede='One less thing to manage on a day that is already full. Your car is where it is supposed to be, when it is supposed to be there, at the price you agreed to before the ride began.',
     image='images/site/svc-minneapolis-car.webp', image_alt='Black Lincoln Continental sedan on a downtown Minneapolis avenue at blue hour with a light-rail train behind', image_caption='Downtown · Uptown · Every Neighborhood',
     intro_eyebrow='What It Means', intro_h2='Car service, private car, luxury car, black car. Same standard.',
     intro=['Clients search for this kind of ride under a lot of names. "Car service" and "private car service" are the umbrella terms for a pre-booked ride with a professional. "Luxury car service" emphasizes the vehicle class. "Black car service" is the term most associated with executive travel, though we use it for personal trips just as often. Whichever you say when you call or book, you get the same thing: a dedicated chauffeur, a dedicated vehicle, and a flat rate agreed before the ride starts.',
            'The distinction that actually matters is how it differs from a rideshare app. Your driver and vehicle are assigned in advance, not matched the moment you request. Your rate does not move because of surge pricing, weather or a downtown event letting out. Your chauffeur is licensed and background-checked, not a part-time gig driver. And the car is a late-model sedan, SUV or Sprinter, inspected and detailed before every trip.'],
     bullets_eyebrow='Included in Every Rate', bullets_h2='What you get, and what you never see',
     bullets=[('A professional licensed chauffeur', 'Uniformed, background-checked, and trained to load your bags and hold the door.'), ('A dedicated vehicle', 'Reserved specifically for your trip. No other passengers, no unrequested stops.'),
              ('Meet-and-greet or curbside pickup', 'Depending on the location, with a text when your chauffeur arrives.'), ('Tolls and standard route fees', 'Built into the flat rate.'),
              ('Water and chargers', 'In every vehicle.'), ('No surge, ever', 'The final price is the one you agreed to when you booked.')],
     steps_h2='How booking works',
     steps=[('Request your ride', 'Online in about two minutes, or call dispatch with pickup, destination, date, time and passenger count.'), ('Get a flat-rate quote', 'You see the price before you confirm.'),
            ('Chauffeur and vehicle assigned', 'A specific chauffeur and car are reserved and you receive the confirmation by email and text.'), ('Your chauffeur arrives early', 'A few minutes ahead, curbside or at the door.'), ('Ride, relax, arrive', 'A fifteen-minute hop across downtown or a run to the suburbs, same rate structure, same standard.')],
     faq=[('What is the difference between black car service and limo service?', 'In practice, very little. Both mean a private, pre-booked, chauffeur-driven ride. "Limo" historically meant a stretch limousine; today most people use it for any professional car service. Our fleet is sedans, SUVs and a Sprinter van under that same standard.'),
          ('How far in advance do I need to book?', 'We recommend 24 hours where possible and three to five days for the Sprinter or busy weekends. Call dispatch for same-day requests.'),
          ('Is this a shared ride?', 'No. Every reservation is private and the vehicle is dedicated to you and your party only.'),
          ('Do you serve the whole Twin Cities metro?', 'Yes. Minneapolis, Saint Paul and every suburb across the metro, plus long-distance runs statewide.'),
          ('Can I book hourly instead of a single trip?', 'Yes. That is our hourly and private chauffeur service, where the car and chauffeur stay with you for a block of time with a four-hour minimum.'),
          ('How do I pay?', 'Card online at booking, or cash or card with your chauffeur. Corporate accounts can be invoiced monthly.')],
     related=rel('p2p', 'chauffeur', 'corp', 'downtown'), cta_h2='Your car, where it is supposed to be.', cta_p='Book online or call dispatch, available around the clock.'),

# ---------------------------------------------------------------- 5. Corporate
dict(file=R['corp'][0], title='Corporate Car Service Minneapolis | Executive Transportation | MSP Chauffeur Service', title_short='Corporate Car Service',
     meta='Corporate car service in Minneapolis with saved traveler profiles, one monthly invoice, cost-center coding and a dedicated account contact. Executive sedans, SUVs and Sprinter vans.',
     keywords='corporate car service Minneapolis, executive transportation Minneapolis, corporate account car service, business travel MSP, executive sedan Minneapolis', service_type='Corporate car service',
     eyebrow='Accounts · Invoicing · Executive Travel', h1='Corporate Car Service in <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Minneapolis</span>',
     lede='A standing arrangement built around how your company actually travels, instead of an assistant calling around and an executive left to sort out their own ride.',
     image='images/site/svc-corporate.webp', image_alt='Two executives stepping out of a black Cadillac Escalade held open by a chauffeur outside a downtown Minneapolis office tower', image_caption='Board Members · Roadshows · Airport Runs',
     intro_eyebrow='What an Account Includes', intro_h2='Fewer receipts, familiar faces',
     intro=['A corporate account replaces ad hoc booking with a program. Saved profiles for your frequent travelers, so a reservation takes a minute instead of re-explaining preferences every time. One consolidated monthly invoice instead of dozens of individual charges for finance to chase. Cost-center or department coding on request. And a dedicated point of contact who already knows your travel patterns rather than a general booking line.',
            'The chauffeurs and vehicles are the same standard as the rest of the house: licensed, professional drivers and late-model sedans, SUVs and a Sprinter, with quiet, connected interiors that support calls and email between stops.'],
     bullets_eyebrow='Why Companies Choose Us', bullets_h2='Predictable, consistent, invoiced once',
     bullets=[('One invoice, not dozens of receipts', 'Finance gets a single consolidated bill each month.'), ('Consistent standard, every trip', 'The same chauffeur and vehicle quality for a routine airport run or a visiting board member.'),
              ('Predictable pricing', 'Flat, quoted rates. No surge during a snowstorm or a downtown event.'), ('A dedicated account contact', 'Someone who knows your routes and your people.'),
              ('Built for repeat use', 'Saved traveler profiles mean your team books in minutes.'), ('Any group size', 'Executive sedan for one, Escalade for three with luggage, Sprinter for a delegation.')],
     steps_h2='How a corporate account works',
     steps=[('Set up your account', 'Tell us your typical routes, frequency and passenger counts and we set up billing terms.'), ('We add your travelers', 'Saved profiles with preferred addresses and vehicles.'),
            ('Book per trip as needed', 'Any authorized employee or assistant can book against the account online, by phone or by email.'), ('One monthly invoice', 'Consolidated, with cost-center coding on request.'), ('A dedicated contact', 'Questions, changes and special requests go to someone who knows your account.')],
     faq=[('How is billing handled?', 'Corporate accounts are invoiced monthly, with cost-center or department coding available on request.'),
          ('Can multiple people at our company book under one account?', 'Yes. Any authorized employee or assistant you designate can book against the account.'),
          ('Do you handle airport pickups for employees?', 'Yes. Every MSP transfer under your account includes flight tracking and terminal pickup; see the MSP Airport Black Car page for details.'),
          ('Can you coordinate a multi-day conference?', 'Yes. Give us the schedule, headcount and locations and we will build a transportation plan, including the Sprinter for larger groups.'),
          ('Is there a minimum monthly volume?', 'No. Accounts are available to companies of any size.'),
          ('How do we set up an account?', 'Call (612) 666-5004 or use the contact page and ask for a corporate account. We will have you set up the same day.')],
     related=rel('chauffeur', 'black', 'group', 'downtown'), cta_h2='Set up the account once. Book in minutes forever.', cta_p='Call dispatch or send a note and we will have your travelers on file today.', cta1='Request an Account', book_qs=''),

# ---------------------------------------------------------------- 6. Limo service
dict(file=R['limo'][0], title='Limo Service Minneapolis | Black Car & Executive SUV | MSP Chauffeur Service', title_short='Limo Service in Minneapolis',
     meta='Limo service in Minneapolis and Saint Paul: the licensed-chauffeur standard in an executive sedan, Escalade or Sprinter for airport runs, nights out, anniversaries and corporate travel. Fixed pricing.',
     keywords='limo service Minneapolis, limousine service Minneapolis, limo to MSP airport, executive limo Minneapolis, black car limo Twin Cities', service_type='Limo service',
     eyebrow='Executive Arrivals · Nights Out · Milestones', h1='Limo Service in <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Minneapolis</span>',
     lede='"Limo" is the everyday word for a private, chauffeur-driven car booked in advance, and most people who say it mean any professional car service. That is exactly what we do, in a sedan, an Escalade or a Sprinter.',
     image='images/site/svc-limousine.webp', image_alt='Chauffeur opening the door of a black Cadillac Escalade for a woman in an evening gown outside a lit theater at night', image_caption='Galas · Anniversaries · The Nights That Matter',
     intro_eyebrow='Limo or Black Car', intro_h2='Same standard either way',
     intro=['Limo, limousine, black car, car service: the underlying promise is identical. A licensed, background-checked chauffeur. A late-model vehicle detailed before every trip. A flat rate agreed before the ride starts. Whichever term you use when you call, that is what arrives.',
            'For the occasions that call for presence, the Cadillac Escalade is the car: three rows of leather, real luggage room and the kind of arrival that gets noticed. For a couple, the Lincoln sedan. For a bridal party or a group night out, the Sprinter with up to ten seats.'],
     bullets_eyebrow='Every Occasion', bullets_h2='Limo service for the days that matter',
     bullets=[('Weddings', 'Escalade for the couple and a Sprinter shuttle for the party and guests, timed to the ceremony and reception.'), ('Prom and nights out', 'A Sprinter for the group, an Escalade for a smaller party, a sober chauffeur for everyone.'),
              ('Anniversaries and milestones', 'Dinner, a show, and a driver who waits so nobody thinks about parking.'), ('Corporate and airport travel', 'A sedan or SUV under the same limo-service standard for business trips and MSP transfers.')],
     steps_h2='Booking the right car for the night',
     steps=[('Tell us the occasion', 'Date, headcount, venues and how long you want the car.'), ('We recommend the vehicle', 'Sedan, Escalade or Sprinter, priced point-to-point or hourly.'),
            ('Confirm the plan', 'Confirmation by email and text with your chauffeur\'s details before the day.'), ('Enjoy it', 'Your chauffeur handles the doors, the route and the timing.')],
     faq=[('What is the difference between a limo and a black car service?', 'In practice, very little. Both mean a private, pre-booked, chauffeur-driven ride. "Limo" historically meant a stretch limousine; today most people use it to mean any professional car service, which is what we provide with sedans, SUVs and a Sprinter.'),
          ('Do you have a stretch limousine?', 'Our fleet is built around late-model executive vehicles: the Lincoln sedan, GMC Yukon, Cadillac Escalade and Mercedes Sprinter. For most occasions the Escalade delivers the experience clients are looking for, with more comfort and none of the parking drama.'),
          ('How far in advance should I book?', 'We recommend 24 hours where possible and three to five days for the Sprinter or busy weekends. Call dispatch for same-day requests.'),
          ('Can I book by the hour?', 'Yes. Hourly service keeps the car and chauffeur with you for the whole evening, with a four-hour minimum.'),
          ('Do you serve Saint Paul and the suburbs?', 'Yes. Our limo service covers Minneapolis, Saint Paul and the surrounding Twin Cities suburbs. See the service area page.')],
     related=rel('hourly', 'chauffeur', 'group', 'downtown'), cta_h2='The right car for the night.', cta_p='Book online or call dispatch, available around the clock.'),

# ---------------------------------------------------------------- 7. Hourly
dict(file=R['hourly'][0], title='Hourly Car Service Minneapolis | Chauffeur by the Hour | MSP Chauffeur Service', title_short='Hourly Car Service',
     meta='Hourly car service in Minneapolis: reserve a chauffeur and luxury vehicle for a block of time. Multi-stop days, meetings, events and sightseeing, with a four-hour minimum and clear hourly rates.',
     keywords='hourly car service Minneapolis, chauffeur by the hour Minneapolis, hourly limo Minneapolis, as directed car service Twin Cities', service_type='Hourly car service',
     eyebrow='As Directed · 4-Hour Minimum', h1='Hourly Car Service in <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Minneapolis</span>',
     lede='Reserve a car and chauffeur for a set number of hours instead of a single trip. Add stops, change the order of your day, run long at dinner. The car waits.',
     image='images/site/svc-hourly.webp', image_alt='Chauffeur waiting beside a black GMC Yukon outside a restaurant in the evening, checking his watch', image_caption='The Car Waits · You Set the Pace', book_qs='?service=hourly', cta1='Book Hourly',
     intro_eyebrow='What It Is', intro_h2='You are in control of the itinerary',
     intro=['Hourly service is a premium option where you reserve the vehicle and chauffeur for a specified duration. Unlike a point-to-point transfer, you can use the car as needed throughout the booking: multiple stops, a sightseeing loop, back-to-back meetings, or a night out across several venues. The rate is calculated by the hour, so the cost is transparent before you start.',
            'Each chauffeur is selected, trained and licensed, with the local knowledge to route around a downtown game letting out or a closed bridge. Hourly bookings run within roughly 20 miles of the Twin Cities so your chauffeur can stay with you the whole time; for a long-distance day, book point-to-point or call dispatch.'],
     bullets_eyebrow='Benefits', bullets_h2='Why clients book by the hour',
     bullets=[('Flexibility', 'Tailor the day on the fly, with unscheduled stops or an extended booking as needed.'), ('Professional chauffeurs', 'Licensed, background-checked and focused on punctuality and comfort.'),
              ('Luxury fleet', 'Sedan, SUV, Escalade or Sprinter, all well maintained, with water and chargers.'), ('Minimum booking', 'Hourly reservations start at four hours.'),
              ('Multi-stop friendly', 'Perfect for errands, tours, meetings and events.'), ('Clear pricing', 'Sedan $75, SUV $90, Premium SUV $110, Sprinter $130 per hour.')],
     steps_h2='How hourly booking works',
     steps=[('Tell us your schedule', 'Start time, estimated hours, first pickup and a general sense of the day.'), ('Get an hourly rate', 'Quoted before you confirm, with a four-hour minimum.'),
            ('Your chauffeur arrives', 'And stays available for the whole booked window, waiting between stops.'), ('Change plans freely', 'Running long or adding a stop does not need a new booking, just tell your chauffeur.')],
     faq=[('What is hourly car service?', 'You book a professional chauffeur and luxury vehicle for a set number of hours instead of a single trip. The chauffeur stays with you for multiple stops, meetings, events or flexible travel within the reserved time.'),
          ('Is there a minimum?', 'Yes. Hourly reservations require a minimum of four hours, which guarantees a dedicated chauffeur for the whole block.'),
          ('Can I change destinations during the ride?', 'Absolutely. Adjust destinations or add stops at any time within the booked window.'),
          ('Is there a distance limit?', 'Hourly bookings stay within about 20 miles of the Twin Cities so the car can remain with you. For Rochester, Duluth or other long-distance trips, book point-to-point instead.'),
          ('Do unused hours get refunded?', 'No. The minimum applies and unused time within the reservation is not refunded, so plan the day to make the most of it.')],
     related=rel('chauffeur', 'p2p', 'limo', 'corp'), cta_h2='Keep the car for the day.', cta_p='Reserve hourly online or call dispatch to talk through your itinerary.'),

# ---------------------------------------------------------------- 8. Private chauffeur
dict(file=R['chauffeur'][0], title='Private Chauffeur & Driver Service Minneapolis | As-Directed | MSP Chauffeur Service', title_short='Private Chauffeur Service',
     meta='Private chauffeur and personal driver service in Minneapolis. Your chauffeur stays with you as directed for full-day itineraries, multi-stop days, events and visiting executives.',
     keywords='private chauffeur Minneapolis, personal driver Minneapolis, as directed car service, private driver Twin Cities, full day chauffeur', service_type='Private chauffeur service',
     eyebrow='One Chauffeur · Your Whole Day', h1='Private Chauffeur &amp; Driver Service in <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Minneapolis</span>',
     lede='A private chauffeur is retained "as directed": the car and driver remain with you for an agreed block of time instead of ending after one drop-off. Your chauffeur waits between stops and drives wherever the day goes.',
     image='images/site/svc-private-chauffeur.webp', image_alt='View from the rear seat of a black Escalade with the chauffeur glancing back and downtown Minneapolis through the windshield', image_caption='As Directed · Waiting Between Stops', book_qs='?service=hourly', cta1='Book Your Chauffeur',
     intro_eyebrow='When It Is the Right Call', intro_h2='For days that do not fit in a single trip',
     intro=['A point-to-point ride is one trip from A to B. A private chauffeur is the right call when your day does not fit that: client visits with unpredictable timing, a full slate of meetings across the metro, a multi-stop celebration, or simply wanting a driver on call without re-booking every leg.',
            'One driver learns your day instead of you re-explaining it at every stop. Plans change and the chauffeur absorbs it without a cancellation fee. And the hourly cost is known before the day starts.'],
     bullets_eyebrow='Common Uses', bullets_h2='Who books a private driver',
     bullets=[('Full-day business itineraries', 'Back-to-back meetings, client visits or a conference day where parking and timing are someone else\'s problem.'), ('Multi-stop personal days', 'Shopping, appointments and errands across the metro with one driver handling all of it.'),
              ('Events and celebrations', 'A driver who stays for the whole night rather than a single drop-off.'), ('Visiting executives and VIPs', 'A dedicated driver for a guest\'s entire stay, on call for their schedule.')],
     steps_h2='How as-directed booking works',
     steps=[('Tell us your schedule', 'Start time, estimated hours, first pickup and a general sense of the day.'), ('Get an hourly rate', 'Quoted with a four-hour minimum, so the cost is known before you confirm.'),
            ('Your chauffeur stays with you', 'At your first pickup and available for the full window, waiting between stops.'), ('Change the day freely', 'Add a stop, run long, reorder the afternoon. Just tell your chauffeur.'), ('Extra time, same rate', 'Past the booked window, additional hours bill at the same clear hourly rate.')],
     faq=[('What is the difference between this and point-to-point?', 'Point-to-point is a single trip from one address to another. A private chauffeur is retained for a block of time and stays with you across multiple stops.'),
          ('Is there a minimum booking time?', 'Yes, four hours. Call dispatch to confirm availability for your date.'),
          ('Can my chauffeur wait while I run into a meeting?', 'Yes. Waiting between stops is the whole point of as-directed service, within your booked window.'),
          ('What if my day runs longer than booked?', 'Additional time is billed at the same hourly rate with no multiplier. Let your chauffeur know as early as possible.'),
          ('Can I request the same chauffeur for repeat bookings?', 'In most cases, yes. Tell dispatch at booking and we will do our best to match you.'),
          ('How do I pay?', 'Card at booking or with your chauffeur. Corporate accounts can be invoiced monthly.')],
     related=rel('hourly', 'corp', 'mpls', 'limo'), cta_h2='One chauffeur. Your whole day.', cta_p='Reserve online or call dispatch, available around the clock.'),

# ---------------------------------------------------------------- 9. Point to point
dict(file=R['p2p'][0], title='Point-to-Point Car Service Minneapolis | Door to Door, Flat Rate | MSP Chauffeur Service', title_short='Point-to-Point Transportation',
     meta='Point-to-point black car service across the Twin Cities: airports, offices, hotels, venues, medical appointments and homes. Flat rates, licensed chauffeurs, no hidden fees.',
     keywords='point to point car service Minneapolis, door to door car service Twin Cities, private ride Minneapolis, flat rate car service Saint Paul', service_type='Point-to-point car service',
     eyebrow='Door to Door · One Flat Rate', h1='Point-to-Point Car Service in <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Minneapolis</span>',
     lede='Reliable, comfortable rides between any two points: airports, downtown offices, hotels, event venues, medical appointments and residential addresses, priced before you confirm.',
     image='images/site/svc-point-to-point.webp', image_alt='Black Lincoln Continental sedan crossing a Mississippi River bridge toward the Minneapolis skyline on an autumn afternoon', image_caption='Any Two Addresses · Metro-Wide',
     intro_eyebrow='What We Do', intro_h2='A direct private ride, quoted upfront',
     intro=['Point-to-point transportation is a direct private ride from one location to another. You give us the two addresses, the date and the time; we give you a flat fare, assign a chauffeur and a vehicle, and text you when the car is outside. Add stops if you need them, at $15 each, and the route runs through every one.',
            'Chauffeurs are licensed, background-checked and trained to be courteous and punctual, and they know the Twin Cities well enough to route around a stalled freeway or a stadium crowd.'],
     bullets_eyebrow='Why Choose It', bullets_h2='What point-to-point gets you',
     bullets=[('Dependability', 'Guaranteed pickup times with live tracking and a professional dispatcher.'), ('Safety', 'Clean, insured vehicles and experienced chauffeurs who follow the rules of the road.'),
              ('Comfort', 'Spacious interiors, climate control and real luggage capacity.'), ('Transparent pricing', 'Flat rates for common routes and no hidden fees.'),
              ('Local expertise', 'Chauffeurs who know Minneapolis streets, traffic patterns and the best routes.'), ('Personalized service', 'Meet & Greet, flight monitoring, child seats and special requests handled.')],
     steps_h2='How it works',
     steps=[('Enter two addresses', 'Pickup and destination, with any extra stops.'), ('See your fare', 'Fixed, before you confirm.'), ('Chauffeur assigned', 'Confirmation by email and text.'), ('Curb to door', 'Your chauffeur arrives early and handles the bags.')],
     faq=[('What is point-to-point transportation?', 'A direct private ride from one location to another. Extra stops can be added at booking.'),
          ('How is it different from hourly service?', 'Point-to-point is a single trip. Hourly keeps the chauffeur with you for multiple stops within a reserved block of time.'),
          ('Can I book in advance?', 'Yes, and we recommend it. Same-day rides are often possible by phone.'),
          ('Do you serve the suburbs?', 'Yes. Minneapolis, Saint Paul and the entire Twin Cities metro, plus long-distance runs statewide.'),
          ('Is pricing upfront?', 'Yes. The booking form shows your exact flat fare before you confirm, with no hidden charges.')],
     related=rel('mpls', 'downtown', 'hourly', 'black'), cta_h2='Two addresses. One fare. Done.', cta_p='Reserve online or call dispatch, available around the clock.'),

# ---------------------------------------------------------------- 10. Group
dict(file=R['group'][0], title='Group Transportation Minneapolis | Sprinter Van Service | MSP Chauffeur Service', title_short='Group Transportation',
     meta='Group transportation in Minneapolis with a Mercedes Sprinter for up to ten passengers and coordinated multi-vehicle service for weddings, conferences, airport groups and events.',
     keywords='group transportation Minneapolis, Sprinter van service Minneapolis, group airport transfer MSP, wedding shuttle Minneapolis, conference transportation Twin Cities', service_type='Group transportation',
     eyebrow='Sprinter · Multi-Vehicle · Coordinated', h1='Group Transportation in <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Minneapolis</span>',
     lede='Coordinating a group requires planning. Our Sprinter seats up to ten with luggage, and when the party is bigger or split across flights we run several vehicles on one reservation so everyone arrives together.',
     image='images/site/svc-group.webp', image_alt='A group of colleagues laughing as they board a black Mercedes Sprinter van outside a hotel entrance', image_caption='Up to Ten Per Sprinter · More Vehicles on Request',
     intro_eyebrow='Who It Is For', intro_h2='Weddings, conferences, teams, airport groups',
     intro=['Wedding parties moving between hotel, ceremony and reception. Sales kickoffs and conference delegations. Sports teams, church groups and family reunions. Airport groups landing on different flights who need to leave MSP as one. We build the schedule with your planner or coordinator and keep every vehicle on it.',
            'Group airport transfers include flight tracking for every inbound, luggage handling at the curb and a single point of contact for the day.'],
     bullets_eyebrow='What We Run', bullets_h2='Group services',
     bullets=[('Wedding guest shuttles', 'Timed loops between hotels, ceremony and reception venues, coordinated with your planner.'), ('Corporate and event transport', 'Conferences, trade shows, offsites and employee shuttles.'),
              ('Airport group transfers', 'Flight tracking for each arrival, luggage handled, everyone leaves together.'), ('Private group outings', 'Concerts, games, breweries and nights out with a sober chauffeur.'),
              ('Multi-vehicle coordination', 'Several Escalades and Sprinters on one reservation with synchronized arrivals.'), ('Group pricing', 'Flat point-to-point fares or hourly blocks, quoted before you confirm.')],
     steps_h2='How we plan a group move',
     steps=[('Share the schedule', 'Headcount, locations, times and any flights.'), ('We size the fleet', 'One Sprinter, or several vehicles on one reservation.'), ('Confirmed plan', 'Every vehicle, chauffeur and pickup time on one confirmation.'), ('Day-of coordination', 'One dispatcher watching every leg.')],
     faq=[('How many passengers can you accommodate?', 'The Sprinter seats up to ten with ten bags. For larger groups we coordinate multiple vehicles, Escalades and Sprinters, on a single reservation.'),
          ('Is group transportation available for corporate travel?', 'Yes. Conferences, offsites, kickoffs and company events, with professional chauffeurs and punctual, coordinated service.'),
          ('Do you offer group airport transfers to MSP?', 'Yes. We track each inbound flight and stage vehicles so the whole group departs together.'),
          ('Can I book multiple vehicles?', 'Absolutely. We manage synchronized arrivals for events, conventions, weddings and corporate gatherings.'),
          ('Is advance booking required?', 'Strongly recommended, especially for larger groups and peak dates. Three to five days ahead for the Sprinter or multi-vehicle bookings.'),
          ('Is there a large-party fee?', 'Bookings of seven or more passengers add a $25 large-party fee, shown before you confirm.')],
     related=rel('hub', 'crew', 'limo', 'corp'), cta_h2='Everyone arrives together.', cta_p='Send us the headcount and the schedule and we will build the plan.'),

# ---------------------------------------------------------------- 11. Downtown
dict(file=R['downtown'][0], title='Downtown Twin Cities Black Car Service | Minneapolis & Saint Paul | MSP Chauffeur Service', title_short='Downtown Twin Cities Black Car',
     meta='Black car service in downtown Minneapolis and downtown Saint Paul for corporate meetings, hotels, games, concerts, dinners and galas. Fixed rates, licensed chauffeurs, on-time arrivals.',
     keywords='downtown Minneapolis car service, downtown Saint Paul black car, black car service Twin Cities, executive transportation downtown Minneapolis', service_type='Downtown black car service',
     eyebrow='Both Downtowns · Curb to Door', h1='Black Car Service in <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Downtown Twin Cities</span>',
     lede='Corporate meetings, hotel pickups, a game at the arena, a concert, a dinner reservation or a gala. Seamless service through the heart of Minneapolis and Saint Paul, at a fixed rate.',
     image='images/site/svc-downtown.webp', image_alt='Black GMC Yukon Denali parked on a downtown Saint Paul street at dusk with the cathedral on the hill behind', image_caption='Minneapolis · Saint Paul · Every Venue Between',
     intro_eyebrow='Downtown Minneapolis', intro_h2='Business districts, hotels, arenas and restaurants',
     intro=['Our downtown Minneapolis service is built for executive travel between offices, the skyway-connected hotels, the arenas and stadiums, the theaters and the restaurants along Nicollet and North Loop. Your chauffeur knows which entrance to use when the game lets out and where the valet line is not.',
            'Downtown Saint Paul gets the same treatment: the Xcel Energy Center, the convention center, Lowertown, the Cathedral Hill hotels and every gala and conference in between, with timely, discreet transportation for corporate clients, event guests and private travelers.'],
     bullets_eyebrow='Ideal For', bullets_h2='What downtown black car is for',
     bullets=[('Corporate meetings', 'Office to office, on time, quiet enough to take a call.'), ('Executive travel', 'Discreet, consistent, the same chauffeur when you want one.'), ('Hotel pickups', 'Every downtown hotel, both cities.'),
              ('Games and concerts', 'Dropped at the door, picked up after, no parking ramp.'), ('Fine dining', 'A reservation, a driver, and a night that does not end with a search for the car.'), ('Airport runs', 'Downtown to MSP with flight tracking, both directions.')],
     steps_h2='How it works downtown',
     steps=[('Book the trip', 'Addresses, date and time, online or by phone.'), ('Fixed fare', 'The rate you see is the rate you pay.'), ('Chauffeur arrives early', 'With a text when the car is at the curb.'), ('Door to door', 'No ramps, no circling, no meters.')],
     faq=[('Can I schedule downtown pickups for business meetings and offices?', 'Absolutely. We provide scheduled pickups and drop-offs for offices, hotels and venues across both downtowns and statewide.'),
          ('Do you offer transportation between downtown and MSP?', 'Yes. Black car service between downtown Minneapolis, downtown Saint Paul and MSP, with flight monitoring in both directions.'),
          ('Are your downtown rates fixed?', 'Yes. The rate quoted at booking is the final price.'),
          ('What vehicles are available?', 'The Lincoln sedan, GMC Yukon, Cadillac Escalade and Mercedes Sprinter, all professionally maintained and detailed.'),
          ('Do you serve both downtown Minneapolis and downtown Saint Paul?', 'Yes, and everything between them, from executive transportation to private chauffeur service and airport transfers.')],
     related=rel('mpls', 'p2p', 'corp', 'black'), cta_h2='Downtown, without the parking.', cta_p='Reserve online or call dispatch, available around the clock.'),

# ---------------------------------------------------------------- 12. Flight crew
dict(file=R['crew'][0], title='Flight Crew Charter Service Minneapolis | Crew Transportation MSP | MSP Chauffeur Service', title_short='Flight Crew Charter Service',
     meta='Ground transportation for airline flight crews at MSP: scheduled hotel and terminal transfers, crew shuttles, layover support and 24/7 availability built around reporting times.',
     keywords='flight crew transportation MSP, airline crew shuttle Minneapolis, crew charter service MSP, crew hotel transfer Minneapolis', service_type='Flight crew transportation',
     eyebrow='Crew Transport · 24/7 · Built Around Reporting Times', h1='Flight Crew Charter Service in <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Minneapolis</span>',
     lede='Aviation professionals keep schedules that do not match the rest of the world\'s. We keep the same ones: precise, tracked, staged early, and available at every hour a flight can land.',
     image='images/site/svc-flight-crew.webp', image_alt='An airline flight crew in uniform loading roller bags into a black Mercedes Sprinter outside a hotel at early morning', image_caption='Hotel to Terminal · Terminal to Hotel · Every Rotation',
     intro_eyebrow='Ground Transportation for Crews', intro_h2='Precision, reliability, and a Sprinter with room for the bags',
     intro=['We specialize in seamless ground transportation for flight crews: punctual, safe and comfortable from the moment the aircraft blocks in. Our dispatch monitors flight status and traffic in real time so the vehicle is at the crew door when the crew is, whether that is a 4 a.m. report or a midnight arrival.',
            'The Sprinter carries a full crew with roller bags in closed-off luggage space; the Escalade and Yukon handle smaller crews. Our team works directly with airlines and crew schedulers to keep every transfer on time and customized to the rotation, with clear, upfront pricing for one-off trips or a standing service agreement.'],
     bullets_eyebrow='Why Crews Choose Us', bullets_h2='What crew transport gets right',
     bullets=[('Precision and reliability', 'Flight status and traffic monitored in real time so the car is ready when you are.'), ('24/7 availability', 'Early departures, late arrivals and everything between.'),
              ('Stress-free booking', 'A standing schedule or a same-day call to dispatch, either works.'), ('Comfortable, modern fleet', 'Quiet, spacious vehicles with room to decompress between flights.'),
              ('Tailored to crews', 'Chauffeurs trained on crew schedules and preferences; dispatch works directly with coordinators.'), ('Transparent pricing', 'Clear, upfront rates for single trips or ongoing agreements.')],
     steps_h2='Crew services',
     steps=[('Airport transfers', 'Between MSP and designated crew hotels or meeting points, any hour.'), ('Crew shuttles', 'Group pickups and drop-offs so no one is left behind and everyone arrives together.'), ('Layover support', 'Multi-leg journeys and extended layovers with transport to multiple destinations or between airports.')],
     faq=[('Do you operate 24/7 for crew transportation?', 'Yes. Flight schedules do not follow office hours and neither do we.'),
          ('Can you accommodate a whole crew at once?', 'Yes. The Sprinter carries up to ten with luggage, and we coordinate additional vehicles for larger crews.'),
          ('Do you work directly with airlines and crew coordinators?', 'Yes. Dispatch coordinates directly with schedulers to keep transfers seamless and customized.'),
          ('What about multi-leg journeys or long layovers?', 'We offer tailored solutions for extended layovers, including transport to multiple destinations within the metro or between airports.'),
          ('Is pricing transparent for ongoing agreements?', 'Yes. Clear, upfront pricing whether it is a one-time trip or a standing service agreement. Call dispatch for a crew rate sheet.')],
     related=rel('hub', 'group', 'black', 'corp'), cta_h2='Built around your reporting time.', cta_p='Call dispatch to set up a crew schedule, or book a one-off transfer online.'),

# ---------------------------------------------------------------- 13. Mayo Clinic
dict(file=R['mayo'][0], title='Mayo Clinic Transportation from Minneapolis | Rochester Car Service | MSP Chauffeur Service', title_short='Mayo Clinic Transportation',
     meta='Private black car transportation between Minneapolis, MSP Airport and Mayo Clinic in Rochester, MN. Direct, non-shared rides for patients and families, flexible scheduling and return trips.',
     keywords='Mayo Clinic transportation, Minneapolis to Rochester car service, MSP to Mayo Clinic, Rochester MN black car, medical transportation Minneapolis', service_type='Long-distance medical transportation',
     eyebrow='Minneapolis · MSP · Rochester', h1='Reliable Black Car Transportation to <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Mayo Clinic</span>',
     lede='Private, direct and comfortable transportation to and from Mayo Clinic in Rochester for patients, families and medical travelers who need the trip to be the easy part.',
     image='images/site/svc-mayo.webp', image_alt='Black Cadillac Escalade on a rural Minnesota highway through autumn farmland at sunrise', image_caption='About 85 Miles · One Flat Fare · Return Trips Scheduled',
     intro_eyebrow='The Rochester Run', intro_h2='Eighty-some miles you should not have to drive',
     intro=['The drive from Minneapolis to Rochester is roughly 85 miles of highway that gets worse in January. Instead of managing the driving, the parking and the weather on top of an appointment, our Minneapolis-to-Mayo service takes you door to door, with a chauffeur who knows the campus entrances and a quiet cabin to rest in.',
            'Flying in? We pick up at MSP with flight tracking and drive straight to Rochester, your hotel or the clinic. Same-day return trips and multi-day appointment schedules can be arranged in advance, and family members ride together in the Escalade or Sprinter.'],
     bullets_eyebrow='Why Patients Choose Us', bullets_h2='Built for medical travel',
     bullets=[('Private, non-shared rides', 'Only your party in the vehicle.'), ('Luxury black car comfort', 'A quiet, climate-controlled cabin for the ride home after a long day.'),
              ('Professional chauffeurs', 'Patient, discreet and familiar with the Mayo campus.'), ('Reliable long-distance service', 'Winter-capable SUVs and a route we drive every week.'),
              ('Flexible scheduling', 'Early appointments, late discharges and waits built around your day.'), ('Return trips', 'Same-day or multi-day, scheduled in advance.')],
     steps_h2='How a Mayo trip works',
     steps=[('Book the dates', 'One-way, same-day return or a multi-day schedule.'), ('Flat fare quoted', 'Minneapolis or MSP to Rochester, priced before you confirm.'), ('Door to door', 'Home, hotel or terminal to the clinic entrance you name.'), ('Return scheduled', 'Your chauffeur waits or returns at the agreed time.')],
     faq=[('Do you provide transportation to Mayo Clinic in Rochester?', 'Yes. Private long-distance chauffeur service from Minneapolis, Saint Paul, the suburbs and MSP Airport.'),
          ('Is this suitable for medical appointments?', 'Yes. The service is designed for appointments, procedures and follow-ups, with comfortable, stress-free and reliable transportation.'),
          ('Can family members ride together?', 'Yes. The Escalade seats six and the Sprinter seats ten, so families travel comfortably in one vehicle.'),
          ('Is the ride direct or shared?', 'All rides are private and direct. We do not offer shared transportation.'),
          ('Do you offer return trips?', 'Yes. Round trips can be scheduled in advance for same-day or multi-day appointments.')],
     related=rel('black', 'p2p', 'area', 'hub'), cta_h2='Let the drive be the easy part.', cta_p='Book your Rochester trip online or call dispatch to schedule a return.'),

# ---------------------------------------------------------------- 14. Chauffeur service Minneapolis
dict(file=R['chmpls'][0], title='Chauffeur Service Minneapolis | Professional Chauffeurs, Luxury Fleet | MSP Chauffeur Service', title_short='Chauffeur Service in Minneapolis',
     meta='Chauffeur service in Minneapolis: a dedicated professional driver focused on your comfort, safety and schedule. Airport transfers, corporate travel and personal trips in late-model luxury vehicles.',
     keywords='chauffeur service Minneapolis, professional chauffeur Minneapolis, luxury chauffeur Twin Cities, chauffeured car service Minneapolis', service_type='Chauffeur service',
     eyebrow='Dedicated · Discreet · Detail-Focused', h1='Chauffeur Service in <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Minneapolis</span>',
     lede='A chauffeur service is more than a ride. You book a dedicated professional whose job is your comfort, your safety and your schedule, and a car that is ready before you are.',
     image='images/site/svc-chauffeur-mpls.webp', image_alt='Portrait of a professional chauffeur in a dark suit, cap and gloves beside a black GMC Yukon with the Minneapolis skyline behind', image_caption='Uniformed · Background-Checked · Trained on the Details',
     intro_eyebrow='The Difference', intro_h2='Getting there versus arriving properly',
     intro=['A regular ride gets you from point A to point B. A chauffeur service prioritizes how you get there: the door held, the bags handled, the route planned around traffic, the cabin set to the temperature you like, and a driver who is early and unobtrusive. Our chauffeurs are trained, background-checked and held to a standard on the first transfer and the fifty-thousandth.',
            'Use it for airport transfers, business meetings, a night out, or a full day as directed. In Minneapolis, Saint Paul or anywhere in Minnesota, the standard travels with the car.'],
     bullets_eyebrow='Our Chauffeur Services', bullets_h2='What we do',
     bullets=[('Airport transfers', 'Flight-tracked pickups at either MSP terminal, with Meet & Greet on request.'), ('Corporate travel', 'Discreet, reliable transportation for meetings, conferences and visiting clients.'),
              ('Personal trips', 'Dinners, shows, celebrations and errands, with the car waiting.'), ('Hourly and as-directed', 'A chauffeur for a block of time, four-hour minimum.')],
     steps_h2='What every chauffeur brings',
     steps=[('Punctuality', 'Ten minutes early, every time.'), ('Discretion', 'Your call is none of our business.'), ('Local knowledge', 'Both terminals, both downtowns, every suburb.'), ('Care', 'Bags loaded, doors held, cabin set right.')],
     faq=[('What makes your chauffeur service different?', 'Professional, uniformed chauffeurs focused on punctuality, discretion and the small details, in late-model luxury vehicles detailed before every trip.'),
          ('Is chauffeur service only for corporate clients?', 'No. It is available for business and personal use alike.'),
          ('Can I book hourly chauffeur service?', 'Yes. Hourly and as-directed bookings start at four hours.'),
          ('Do chauffeurs assist with luggage?', 'Yes. Full luggage assistance is included on every trip.'),
          ('Are vehicles cleaned regularly?', 'Every vehicle is cleaned and detailed before each ride.')],
     related=rel('chauffeur', 'hourly', 'black', 'corp'), cta_h2='Arrive properly.', cta_p='Reserve online or call dispatch, available around the clock.'),

# ---------------------------------------------------------------- 15. Mall of America
dict(file=R['moa'][0], title='Mall of America Car Service | Bloomington & MSP Transfers | MSP Chauffeur Service', title_short='Mall of America Car Service',
     meta='Private car service to Mall of America and Bloomington hotels from anywhere in the Twin Cities, plus MSP Airport transfers with flight tracking. Flat rates, SUVs with room for the bags.',
     keywords='Mall of America car service, Bloomington car service, MSP to Mall of America, MOA transportation, Bloomington hotel car service', service_type='Mall of America car service',
     eyebrow='Bloomington · MOA · MSP', h1='Mall of America <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Car Service</span>',
     lede='Door-to-door service to Mall of America and the Bloomington hotels from anywhere in the metro, and flight-tracked transfers between MSP and MOA, which sit only a few minutes apart.',
     image='images/site/svc-moa.webp', image_alt='Black GMC Yukon at a large mall entrance with a chauffeur loading shopping bags while a family waits', image_caption='Room for the Bags · Return Pickup Scheduled',
     intro_eyebrow='Bloomington Service', intro_h2='Shopping, dining, events and the airport next door',
     intro=['Families planning a shopping day, couples on a weekend getaway, executives meeting near the mall: we provide private, pre-scheduled transportation designed around your schedule, not the other way around. A sedan for a personal visit, or the Yukon and Escalade when there will be bags, strollers and purchases on the way home.',
            'For travelers flying into MSP, we offer seamless transfers between the airport and the Bloomington hotels, convention spaces and offices around MOA. Flight monitoring accommodates delays and early arrivals, so the ride is dependable without the uncertainty of a hailed ride.'],
     bullets_eyebrow='Our MOA Services', bullets_h2='What we run around the mall',
     bullets=[('Mall of America transfers', 'Door to door from anywhere in the Twin Cities metro.'), ('MSP pickup and drop-off', 'Flight tracking and Meet & Greet options, a few minutes away.'),
              ('Hotel and corporate transport', 'Bloomington hotels, offices and event spaces.'), ('Hourly charters', 'A chauffeur who waits while you shop, dine or attend an event.'),
              ('Group outings', 'The Sprinter for shopping groups and conventions.'), ('Flat rates', 'No hidden fees, quoted before you confirm.')],
     steps_h2='How a mall run works',
     steps=[('Book the pickup', 'Home, hotel or terminal.'), ('Flat fare', 'Quoted upfront.'), ('Shop, dine, wander', 'Schedule a return time or keep the car hourly.'), ('Bags in, home', 'Your chauffeur loads the purchases.')],
     faq=[('Do you provide transportation to Mall of America?', 'Yes. Direct private transportation to MOA from anywhere in Minneapolis, Saint Paul or the surrounding areas.'),
          ('Can I schedule a return pickup?', 'Yes. Round-trip booking lets you schedule the return in advance so you never wait for a ride.'),
          ('Do you serve hotels near MOA?', 'Absolutely. Hotel pickups and drop-offs across Bloomington.'),
          ('Is this good for shopping groups?', 'Yes. The Yukon, Escalade and Sprinter give shopping groups and families room for passengers and purchases.'),
          ('Are rates flat to Bloomington?', 'Yes. Transparent flat-rate pricing with no hidden fees; the booking form shows your exact fare.')],
     related=rel('pickup', 'p2p', 'hourly', 'group'), cta_h2='Room for the bags, and the way home.', cta_p='Reserve online or call dispatch, available around the clock.'),

# ---------------------------------------------------------------- 16. Service area
dict(file=R['area'][0], title='Service Area | Twin Cities, Minnesota and Beyond | MSP Chauffeur Service', title_short='Service Area',
     meta='MSP Chauffeur Service covers Minneapolis, Saint Paul, every Twin Cities suburb and long-distance runs across Minnesota and Wisconsin. Wherever you need to go, we will take you.',
     keywords='car service service area Minneapolis, Twin Cities suburbs car service, long distance car service Minnesota, Duluth car service, St Cloud car service, Rochester car service', service_type='Chauffeured transportation',
     eyebrow='Twin Cities · Minnesota · Beyond', h1='We Will Take You <span class="text-transparent bg-clip-text bg-gradient-to-r from-oxblood-300 via-oxblood-400 to-oxblood-500">Anywhere</span>',
     lede='Wherever the journey goes, the service goes with it. Across the metro, across the state or across the border, your ground transportation is handled with the same precision and the same chauffeur standard.',
     image='images/site/svc-service-area.webp', image_alt='Black Cadillac Escalade on an open Minnesota highway winding past lakes and pine forest in late afternoon light', image_caption='Seven Counties · Statewide · Western Wisconsin',
     intro_eyebrow='Coverage', intro_h2='Every suburb, both downtowns, and the long roads out',
     intro=['Our home turf is the seven-county Twin Cities metro: Minneapolis, Saint Paul and every suburb from Albertville to Woodbury. Point-to-point, hourly and airport service run across all of it at fixed fares.',
            'Beyond the metro we regularly drive Rochester and Mayo Clinic, Duluth, St. Cloud, Mankato, Northfield, Stillwater and Hudson, and we take longer trips on request, priced as flat point-to-point fares so there is no surprise at the end. For a destination not on the list, call dispatch and we will quote it.'],
     bullets_eyebrow='Cities We Serve', bullets_h2='Across the metro and beyond',
     bullets=[('Minneapolis and Saint Paul', 'Both downtowns, every neighborhood, the University area and the airport.'),
              ('West Metro', 'Edina, Minnetonka, Wayzata, Plymouth, Maple Grove, Eden Prairie, Chanhassen, Excelsior, Orono, Long Lake, Medina, Golden Valley, St. Louis Park, Hopkins.'),
              ('South Metro', 'Bloomington, Richfield, Burnsville, Apple Valley, Eagan, Lakeville, Savage, Prior Lake, Shakopee, Rosemount, Farmington, Inver Grove Heights.'),
              ('East Metro', 'Woodbury, Stillwater, Oakdale, Maplewood, Cottage Grove, Lake Elmo, Afton, Hastings, White Bear Lake, Mahtomedi, Hudson (WI).'),
              ('North Metro', 'Blaine, Coon Rapids, Anoka, Andover, Brooklyn Park, Fridley, Roseville, Shoreview, Arden Hills, Lino Lakes, Forest Lake, Elk River, Rogers.'),
              ('Long distance', 'Rochester and Mayo Clinic, Duluth, St. Cloud, Mankato, Northfield, Red Wing, Brainerd and points beyond, quoted flat.')],
     steps_h2='How out-of-town trips work',
     steps=[('Name the destination', 'Any address in Minnesota or across the border.'), ('Flat fare', 'Quoted point-to-point before you confirm, tolls included.'), ('Winter-ready', 'Full-size SUVs and chauffeurs who drive I-35 in January.'), ('Return scheduled', 'Same day or another day, on the same reservation.')],
     faq=[('Do you serve the whole Twin Cities metro?', 'Yes. Minneapolis, Saint Paul and every suburb across the seven-county metro.'),
          ('Do you go outside the metro?', 'Yes. Rochester, Duluth, St. Cloud, Mankato, western Wisconsin and beyond, priced as flat point-to-point fares.'),
          ('Is there a distance limit?', 'Not for point-to-point service. Hourly bookings stay within about 20 miles of the Twin Cities so the chauffeur can remain with you; longer days are quoted point-to-point.'),
          ('Do you charge extra for suburbs?', 'No. Fares are calculated on the routed distance, so a suburb pays the same per-mile rate as downtown.'),
          ('What if my town is not listed?', 'Call (612) 666-5004. If it is reachable by road, we will quote it.')],
     related=rel('mayo', 'p2p', 'black', 'hourly'), cta_h2='Name the place. We will be there.', cta_p='Reserve online or call dispatch, available around the clock.'),
]
